version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cloud.google.com/go/pubsub
    versions:
    - 1.10.1
    - 1.10.2
  - dependency-name: github.com/gofiber/fiber/v2
    versions:
    - 2.6.0
